(define (domain blocks-world)
    (:constants Table)
    (:action Move
        :parameters (?block ?from ?toBlock)
        :precondition (and
            (Block ?block)
            (Block ?toBlock)
            (not (= ?block ?from))
            (not (= ?block ?toBlock))
            (not (= ?from ?toBlock))
            (On ?block ?from)
            (Clear ?block)
            (Clear ?toBlock)
        )
        :effect (and
            (On ?block ?toBlock)
            (Clear ?from)
            (not (On ?block ?from))
            (not (Clear ?toBlock))
        )
    )
    (:action MoveToTable
        :parameters (?block ?from)
        :precondition (and
            (Block ?block)
            (not (= ?block ?from))
            (not (= ?from Table))
            (On ?block ?from)
            (Clear ?block)
        )
        :effect (and
            (On ?block Table)
            (Clear ?from)
            (not (On ?block ?from))
        )
    )
)
