name: Validation Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Run Tests
      working-directory: ./src
      run: dotnet test